# Generated by Django 4.1.1 on 2022-10-01 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='choice',
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('card', 'karta'), ('cash', 'gotówka'), ('transfer', 'przelew')], max_length=8),
        ),
    ]
